/**
 * Shared feed list + display metadata (keep in sync with any FEEDS edits).
 */
module.exports.FEEDS = [
  { url: 'https://thehill.com/homenews/administration/feed/', source: 'The Hill Administration', cat: 'white-house', tags: ['executive', 'policy'] },
  { url: 'https://feeds.reuters.com/reuters/politicsNews', source: 'Reuters Politics', cat: 'white-house', tags: ['white house', 'politics'] },
  { url: 'https://rss.politico.com/politics-news.xml', source: 'Politico', cat: 'white-house', tags: ['white house', 'dc'] },
  { url: 'https://rss.politico.com/congress.xml', source: 'Politico Congress', cat: 'congress', tags: ['congress', 'hearings'] },
  { url: 'https://thehill.com/homenews/senate/feed/', source: 'The Hill Senate', cat: 'congress', tags: ['senate', 'hearings'] },
  { url: 'https://thehill.com/homenews/house/feed/', source: 'The Hill House', cat: 'congress', tags: ['house', 'hearings'] },
  { url: 'https://rollcall.com/feed/', source: 'Roll Call', cat: 'congress', tags: ['congress', 'legislation'] },
  { url: 'https://www.federalregister.gov/api/v1/documents.rss?conditions%5Btype%5D%5B%5D=RULE&conditions%5Btype%5D%5B%5D=PROPOSED_RULE', source: 'Federal Register — Rules & proposed', cat: 'federal-register', tags: ['rulemaking', 'regulations'] },
  { url: 'https://www.federalregister.gov/api/v1/documents.rss?conditions%5Btype%5D%5B%5D=NOTICE', source: 'Federal Register — Notices', cat: 'federal-register', tags: ['notice', 'federal'] },
  { url: 'https://www.federalregister.gov/api/v1/documents.rss?conditions%5Btype%5D%5B%5D=PRESDOCU', source: 'Federal Register — Presidential', cat: 'federal-register', tags: ['presidential', 'executive'] },
  { url: 'https://www.federalregister.gov/api/v1/public_inspection_documents.rss', source: 'Federal Register — Public Inspection', cat: 'federal-register', tags: ['public inspection', 'upcoming'] },
  { url: 'https://feeds.reuters.com/reuters/topNews', source: 'Reuters Top', cat: 'dhs', tags: ['us'] },
  { url: 'https://feeds.reuters.com/reuters/domesticNews', source: 'Reuters Domestic', cat: 'dhs', tags: ['dhs', 'homeland security', 'domestic'] },
  { url: 'https://www.dhs.gov/rss.xml', source: 'DHS', cat: 'dhs', tags: ['homeland'] },
  { url: 'https://www.cbp.gov/rss/newsroom', source: 'CBP Newsroom', cat: 'dhs', tags: ['border', 'newsroom'] },
  /** Official State Dept RSS directory: https://www.state.gov/rss-feeds */
  { url: 'https://www.state.gov/rss-feed/africa/feed/', source: 'State — Africa', cat: 'state-dept', tags: ['africa', 'region'] },
  { url: 'https://www.state.gov/rss-feed/collected-department-releases/feed/', source: 'State — Collected releases', cat: 'state-dept', tags: ['state', 'news'] },
  { url: 'https://www.state.gov/rss-feed/department-press-briefings/feed/', source: 'State — Press briefings', cat: 'state-dept', tags: ['briefing', 'media'] },
  { url: 'https://www.state.gov/rss-feed/diplomatic-security/feed/', source: 'State — Diplomatic Security', cat: 'state-dept', tags: ['security'] },
  { url: 'https://www.state.gov/rss-feed/direct-line-to-american-business/feed/', source: 'State — Direct Line (business)', cat: 'state-dept', tags: ['business', 'trade'] },
  { url: 'https://www.state.gov/rss-feed/east-asia-and-the-pacific/feed/', source: 'State — East Asia & Pacific', cat: 'state-dept', tags: ['asia', 'pacific'] },
  { url: 'https://www.state.gov/rss-feed/europe-and-eurasia/feed/', source: 'State — Europe & Eurasia', cat: 'state-dept', tags: ['europe'] },
  { url: 'https://www.state.gov/rss-feed/international-organizations/feed/', source: 'State — International organizations', cat: 'state-dept', tags: ['multilateral', 'un'] },
  { url: 'https://www.state.gov/rss-feed/near-east/feed/', source: 'State — Near East', cat: 'state-dept', tags: ['middle east'] },
  { url: 'https://www.state.gov/rss-feed/press-releases/feed/', source: 'State — Press releases', cat: 'state-dept', tags: ['press', 'state'] },
  { url: 'https://www.state.gov/rss-feed/public-schedule/feed/', source: 'State — Public schedule', cat: 'state-dept', tags: ['schedule'] },
  { url: 'https://www.state.gov/rss-feed/secretarys-remarks/feed/', source: 'State — Secretary’s remarks', cat: 'state-dept', tags: ['secretary', 'policy'] },
  { url: 'https://www.state.gov/rss-feed/south-and-central-asia/feed/', source: 'State — South & Central Asia', cat: 'state-dept', tags: ['asia', 'south asia'] },
  { url: 'https://travel.state.gov/_res/rss/TAsTWs.xml', source: 'State — Travel advisories', cat: 'state-dept', tags: ['travel', 'advisories'] },
  { url: 'https://www.state.gov/rss-feed/treaties-new/feed/', source: 'State — Treaties (TIAS)', cat: 'state-dept', tags: ['treaties', 'law'] },
  { url: 'https://www.state.gov/rss-feed/western-hemisphere/feed/', source: 'State — Western Hemisphere', cat: 'state-dept', tags: ['americas', 'latin america'] },
  { url: 'https://feeds.reuters.com/reuters/businessNews', source: 'Reuters Business', cat: 'treasury', tags: ['treasury', 'markets'] },
  { url: 'https://feeds.bloomberg.com/markets/news.rss', source: 'Bloomberg Markets', cat: 'treasury', tags: ['treasury', 'markets'] },
  { url: 'https://www.bis.doc.gov/index.php/all-articles?format=feed&type=rss', source: 'BIS', cat: 'commerce', tags: ['export controls', 'entity list', 'bis'] },
  { url: 'https://www.commerce.gov/news/rss', source: 'Commerce Dept', cat: 'commerce', tags: ['commerce', 'trade'] },
  { url: 'https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=1&Site=945&Category=', source: 'DOD', cat: 'dod', tags: ['defense', 'military'] },
  { url: 'https://breakingdefense.com/feed/', source: 'Breaking Defense', cat: 'dod', tags: ['defense', 'military'] },
  { url: 'https://www.wto.org/rss/english/news_e.rss', source: 'WTO', cat: 'trade', tags: ['wto', 'trade'] },
  { url: 'https://rss.politico.com/trade.xml', source: 'Politico Trade', cat: 'trade', tags: ['ustr', 'trade rep'] },
  { url: 'https://www.freightwaves.com/news/feed', source: 'FreightWaves', cat: 'supply-chain', tags: ['freight', 'logistics'] },
  { url: 'https://www.supplychainbrain.com/rss/articles', source: 'Supply Chain Brain', cat: 'supply-chain', tags: ['supply chain', 'logistics'] },
  { url: 'https://www.logisticsmgmt.com/rss/articles', source: 'Logistics Management', cat: 'supply-chain', tags: ['logistics', 'supply chain'] },
  { url: 'https://www.joc.com/rss.xml', source: 'JOC', cat: 'supply-chain', tags: ['shipping', 'ports'] },
  { url: 'https://semiconductors.org/news/feed', source: 'SIA', cat: 'supply-chain', tags: ['semiconductors', 'chips'] },
  /** OFAC XML at home.treasury.gov redirects; Treasury News RSS covers sanctions press. */
  { url: 'https://feeds.feedburner.com/TreasuryNews', source: 'Treasury News', cat: 'sanctions', tags: ['sanctions', 'ofac', 'treasury'] },
  { url: 'https://www.justice.gov/news/rss', source: 'DOJ', cat: 'sanctions', tags: ['enforcement', 'doj', 'fcpa'] },
  { url: 'https://acamstoday.org/feed/', source: 'ACAMS', cat: 'sanctions', tags: ['aml', 'compliance'] },
  { url: 'https://www.trackingterrorism.org/rss.xml', source: 'Tracking Terrorism', cat: 'sanctions', tags: ['terrorism', 'sanctions'] },
  { url: 'https://www.atlanticcouncil.org/feed/', source: 'Atlantic Council', cat: 'geopolitics', tags: ['geopolitics', 'security'] },
  { url: 'https://www.brookings.edu/feed/', source: 'Brookings', cat: 'geopolitics', tags: ['national security', 'policy'] },
  { url: 'https://www.chathamhouse.org/feed/rss.xml', source: 'Chatham House', cat: 'geopolitics', tags: ['foreign relations', 'geopolitics'] },
  { url: 'https://feeds.bbci.co.uk/news/world/rss.xml', source: 'BBC World', cat: 'geopolitics', tags: ['world', 'geopolitics'] },
  { url: 'https://www.theguardian.com/world/rss', source: 'Guardian World', cat: 'geopolitics', tags: ['world news', 'breaking'] },
  { url: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', source: 'NYT World', cat: 'geopolitics', tags: ['world', 'geopolitics'] },
  { url: 'https://feeds.reuters.com/reuters/CNtopNews', source: 'Reuters China', cat: 'china', tags: ['china', 'beijing'] },
  { url: 'https://www.scmp.com/rss/91/feed', source: 'SCMP', cat: 'china', tags: ['china', 'hong kong'] },
  { url: 'https://thechinaproject.com/feed/', source: 'The China Project', cat: 'china', tags: ['china', 'policy'] },
  { url: 'https://cisa.gov/cybersecurity-advisories/all.xml', source: 'CISA', cat: 'tech-ai', tags: ['cybersecurity', 'cisa'] },
  { url: 'https://feeds.wired.com/wired/index', source: 'Wired', cat: 'tech-ai', tags: ['tech', 'ai'] },
  { url: 'https://rss.politico.com/technology.xml', source: 'Politico Tech', cat: 'tech-ai', tags: ['tech policy', 'ai regulation'] },
  { url: 'https://feeds.reuters.com/reuters/technologyNews', source: 'Reuters Tech', cat: 'tech-ai', tags: ['technology', 'ai'] },
  { url: 'https://techcrunch.com/feed/', source: 'TechCrunch', cat: 'tech-ai', tags: ['startups', 'tech'] },
  { url: 'https://www.theverge.com/rss/index.xml', source: 'The Verge', cat: 'tech-ai', tags: ['tech', 'policy'] },
  { url: 'https://www.federalreserve.gov/feeds/press_all.xml', source: 'Federal Reserve', cat: 'finance', tags: ['fed', 'interest rates'] },
  { url: 'https://www.imf.org/en/News/rss?language=eng', source: 'IMF', cat: 'finance', tags: ['imf', 'global economy'] },
  { url: 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', source: 'WSJ Markets', cat: 'finance', tags: ['markets', 'wsj'] },
  { url: 'https://www.oecd.org/newsroom/rss/', source: 'OECD', cat: 'finance', tags: ['oecd', 'economy'] },
  { url: 'https://oilprice.com/rss/main', source: 'OilPrice.com', cat: 'energy', tags: ['oil', 'gas', 'energy'] },
  { url: 'https://www.mining.com/feed/', source: 'Mining.com', cat: 'energy', tags: ['mining', 'metals'] },
  { url: 'https://spglobal.com/commodityinsights/en/rss', source: 'S&P Commodity', cat: 'energy', tags: ['commodities', 'energy'] },
  { url: 'https://www.eia.gov/rss/news.xml', source: 'EIA', cat: 'energy', tags: ['energy', 'oil', 'gas'] },
  { url: 'https://www.defensenews.com/arc/outboundfeeds/rss/', source: 'Defense News', cat: 'defense', tags: ['defense', 'industry'] },
  { url: 'https://rss.politico.com/huddle.xml', source: 'Politico Huddle', cat: 'dc-politics', tags: ['dc', 'staff', 'appointments'] },
  { url: 'https://thehill.com/feed/', source: 'The Hill', cat: 'dc-politics', tags: ['dc', 'politics'] },
  { url: 'https://axios.com/feeds/feed.rss', source: 'Axios', cat: 'dc-politics', tags: ['politics', 'dc'] },
  { url: 'https://www.govexec.com/rss/all/', source: 'GovExec', cat: 'dc-politics', tags: ['government', 'appointments', 'federal'] },
  { url: 'https://ec.europa.eu/commission/presscorner/api/rss', source: 'EU Commission', cat: 'intl-reg', tags: ['eu', 'regulation'] },
  { url: 'https://www.fatf-gafi.org/en/publications/rss.xml', source: 'FATF', cat: 'intl-reg', tags: ['fatf', 'aml'] },
  { url: 'https://www.wcoomd.org/en/media/newsroom/rss.xml', source: 'WCO', cat: 'intl-reg', tags: ['customs', 'wco'] },
  { url: 'https://ico.org.uk/about-the-ico/news-and-events/rss/', source: 'ICO (UK)', cat: 'intl-reg', tags: ['gdpr', 'data privacy'] },
];

module.exports.CAT_META = {
  'white-house': { label: 'White House', color: '#E8401C' },
  congress: { label: 'Congress & Hearings', color: '#C49A2A' },
  'federal-register': { label: 'Federal Register', color: '#2563EB' },
  dhs: { label: 'DHS & Border', color: '#94A3B8' },
  'state-dept': { label: 'State Department', color: '#16A34A' },
  treasury: { label: 'Treasury / OFAC', color: '#E8401C' },
  commerce: { label: 'Commerce / BIS', color: '#C49A2A' },
  dod: { label: 'DOD & Pentagon', color: '#2563EB' },
  trade: { label: 'Trade & Tariffs', color: '#94A3B8' },
  'supply-chain': { label: 'Supply Chain', color: '#16A34A' },
  sanctions: { label: 'Sanctions & Compliance', color: '#E8401C' },
  geopolitics: { label: 'Geopolitics', color: '#C49A2A' },
  china: { label: 'China', color: '#2563EB' },
  'tech-ai': { label: 'Tech & AI', color: '#16A34A' },
  finance: { label: 'Finance & Markets', color: '#E8401C' },
  energy: { label: 'Energy & Commodities', color: '#C49A2A' },
  defense: { label: 'Defense Industry', color: '#2563EB' },
  'dc-politics': { label: 'DC Politics & Appointments', color: '#94A3B8' },
  'intl-reg': { label: 'Intl Regulatory', color: '#16A34A' },
};

module.exports.PRIORITY_KEYWORDS = [
  'appointed', 'nomination', 'confirmed', 'executive order', 'sanctions', 'emergency',
  'tariff', 'export control', 'entity list', 'indicted', 'arrested', 'seized',
  'declared', 'breach', 'shutdown', 'default',
  'mullen', 'doge', 'cfius', 'uflpa', 'ofac', 'ban', 'blocked', 'expelled',
];
